import type { Metadata } from 'next'
// import './globals.css'
import { APP_NAME } from '@/lib/constants'
import Header from '@/components/shared/header'
import Footer from '@/components/footer'

export const metadata: Metadata = {
  title: {
    template: '%s | Prostore',
    default: APP_NAME
  },
  description: 'Generated by create next app'
}
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className='flex h-screen flex-col'>
      <Header></Header>
      <main className='flex-1 main'>{children}</main>
      <Footer></Footer>
    </div>
  )
}
